apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
      - name: accounts
        image: microservices/accounts
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080