version: "3.8"

services:

  configserver:
    image: froztfire/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - froztfire

  accounts:
    image: froztfire/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - froztfire
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  loans:
    image: froztfire/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - froztfire
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  cards:
    image: froztfire/cards:latest
    mem_limit: 700m
    ports:
      - "9001:9000"
    networks:
      - froztfire
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

networks:
  froztfire:
